-- AlterTable
ALTER TABLE "Payroll" ADD COLUMN     "grossSalary" DOUBLE PRECISION NOT NULL DEFAULT 0.0,
ADD COLUMN     "incomeTax" DOUBLE PRECISION NOT NULL DEFAULT 0.0,
ADD COLUMN     "sgkEmployerPay" DOUBLE PRECISION NOT NULL DEFAULT 0.0,
ADD COLUMN     "sgkWorkerPay" DOUBLE PRECISION NOT NULL DEFAULT 0.0,
ADD COLUMN     "stampTax" DOUBLE PRECISION NOT NULL DEFAULT 0.0,
ADD COLUMN     "totalEmployerCost" DOUBLE PRECISION NOT NULL DEFAULT 0.0,
ADD COLUMN     "unemploymentEmployer" DOUBLE PRECISION NOT NULL DEFAULT 0.0,
ADD COLUMN     "unemploymentWorker" DOUBLE PRECISION NOT NULL DEFAULT 0.0;

-- CreateTable
CREATE TABLE "Allowance" (
    "id" TEXT NOT NULL,
    "employeeId" TEXT NOT NULL,
    "name" TEXT NOT NULL,
    "amount" DOUBLE PRECISION NOT NULL,
    "periodType" TEXT NOT NULL,
    "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updatedAt" TIMESTAMP(3) NOT NULL,

    CONSTRAINT "Allowance_pkey" PRIMARY KEY ("id")
);

-- AddForeignKey
ALTER TABLE "Allowance" ADD CONSTRAINT "Allowance_employeeId_fkey" FOREIGN KEY ("employeeId") REFERENCES "Employee"("id") ON DELETE CASCADE ON UPDATE CASCADE;
